# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://strong-type.systems" # the base hostname & protocol for your site, e.g. http://example.com
# use commit hash!
repository: strong-type-systems/strong-type.systems
# Build settings
markdown: kramdown
# theme: minima

plugins:
  - jekyll-optional-front-matter
  - jekyll-github-metadata


defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      order: 100
      listed: true
      styles:
        - ./style/fonts/fonts.css
        - ./style/main.css
      modules:
        - ./js/main.mjs


include:
  - README.md
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - design
  - vendor
  - ruby_bundle
  - venv
  - Gemfile
  - Gemfile.lock
  - node_modules
  - varla-varfo
  - generate_media_queries.py
  - serveloacally.sh

#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
